// Generated by Year Timelines
window.TIMELINES_DEFAULT = {
  timelines: [
  {
    "id": "tl_personal",
    "title": "Personal Milestones",
    "color": "#ff006e",
    "events": [
      {
        "year": "1994",
        "title": "Born",
        "desc": "",
        "image": "pkmn/1.webp"
      },
      {
        "year": "2012",
        "title": "Graduated",
        "desc": "High school",
        "image": "pkmn/2.webp"
      },
      {
        "year": "2016",
        "title": "First Job",
        "desc": "Junior developer",
        "image": "pkmn/3.webp"
      },
      {
        "year": "2025",
        "title": "New Project",
        "desc": "Years-only timelines launched!",
        "image": "pkmn/3M.webp"
      }
    ]
  },
  {
    "id": "tl_447i6p",
    "title": "Mainline Games",
    "color": "#8aa",
    "events": [
      {
        "year": "1996",
        "title": "Red / Blue",
        "desc": "Team Rocket forces pokemon to evolve with radio waves.",
        "image": "games/red.webp"
      },
      {
        "year": "1998",
        "title": "Yellow",
        "desc": "",
        "image": "games/yellow.webp"
      },
      {
        "year": "1999",
        "title": "Gold / Silver",
        "desc": "",
        "image": "games/gold.webp"
      },
      {
        "year": "2000",
        "title": "Crystal",
        "desc": "",
        "image": "games/crystal.webp"
      },
      {
        "year": "2002",
        "title": "Ruby / Sapphire",
        "desc": "",
        "image": "games/ruby.webp"
      },
      {
        "year": "1996",
        "title": "Fire Red / Leaf Green",
        "desc": "",
        "image": "games/leaf-green.webp"
      },
      {
        "year": "2004",
        "title": "Emerald",
        "desc": "",
        "image": "games/emerald.webp"
      },
      {
        "year": "2006",
        "title": "Diamond / Pearl",
        "desc": "",
        "image": "games/diamond.webp"
      },
      {
        "year": "2008",
        "title": "Platinum",
        "desc": "",
        "image": "games/platinum.webp"
      },
      {
        "year": "1999",
        "title": "Heart Gold / Soul Silver",
        "desc": "",
        "image": "games/soul-silver.webp"
      },
      {
        "year": "2010",
        "title": "Black / White",
        "desc": "",
        "image": "games/black.webp"
      },
      {
        "year": "2012",
        "title": "Black 2 / White 2",
        "desc": "",
        "image": "games/white-2.webp"
      },
      {
        "year": "2013",
        "title": "X / Y",
        "desc": "",
        "image": "games/x.webp"
      },
      {
        "year": "2002",
        "title": "Omega Rub / Alpha Sapphire",
        "desc": "",
        "image": "games/alpha-sapphire.webp"
      },
      {
        "year": "2016",
        "title": "Sun / Moon",
        "desc": "",
        "image": "games/sun.webp"
      },
      {
        "year": "2017",
        "title": "Ultra Sun / Ultra Moon",
        "desc": "",
        "image": "games/ultra-moon.webp"
      },
      {
        "year": "2019",
        "title": "Sword / Shield",
        "desc": "",
        "image": "games/sword.webp"
      },
      {
        "year": "2006",
        "title": "Brilliant Diamond / Shining Pearl",
        "desc": "",
        "image": "games/shining-pearl.webp"
      },
      {
        "year": "1871",
        "title": "Legends Arceus",
        "desc": "",
        "image": "games/legends-arceus.webp"
      },
      {
        "year": "2022",
        "title": "Scarlet / Violet",
        "desc": "",
        "image": "games/scarlet.webp"
      },
      {
        "year": "2025",
        "title": "Legends Z-A",
        "desc": "",
        "image": "games/legends-za.webp"
      },
      {
        "year": "3000000bc",
        "title": "Creation...",
        "desc": "",
        "image": "pkmn/493.webp"
      }
    ]
  }
]
};
